<a href="https://colab.research.google.com/github/RheedWhan/AltSchool_DataScience_2023/blob/main/Data_Cleaning_with_Python___LMS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Extracting Dataset

In [274]:
# import libraries

import pandas as pd

In [275]:
# create a dataset

url_link1 = 'https://en.wikipedia.org/wiki/List_of_largest_companies_by_revenue'
company_data = pd.read_html(url_link1)

In [276]:
type(company_data)

list

In [277]:
company_data = company_data[0]

In [278]:
type(company_data)

pandas.core.frame.DataFrame

In [279]:
company_data.head()

,Rank,Name,Industry,Revenue,Profit,Employees,Headquarters[note 1],State-owned,Ref.,Unnamed: 9_level_0
,Rank,Name,Industry,USD millions,USD millions,Employees,Headquarters[note 1],State-owned,Revenue per worker,Revenue per worker
0,1,Walmart,Retail,"$611,289","$11,680",2100000,United States,NaN,[1],"291.090,00"
1,2,Saudi Aramco,Oil and gas,"$603,651","$159,069",70496,Saudi Arabia,NaN,[4],"8.562.911,37"
2,3,State Grid Corporation of China,Electricity,"$530,009","$8,192",870287,China,NaN,[5],"609.004,85"
3,4,Amazon,Retail,"$513,983","−$2,722",1541000,United States,NaN,[6],"333.538,61"
4,5,Vitol,Commodities,"$505,000","$15,000",1560,Switzerland,NaN,[7][8],"323.717.948,72"

In [280]:
company_data.columns

MultiIndex([(                'Rank',                 'Rank'),
            (                'Name',                 'Name'),
            (            'Industry',             'Industry'),
            (             'Revenue',         'USD millions'),
            (              'Profit',         'USD millions'),
            (           'Employees',            'Employees'),
            ('Headquarters[note 1]', 'Headquarters[note 1]'),
            (         'State-owned',          'State-owned'),
            (                'Ref.',   'Revenue per worker'),
            (  'Unnamed: 9_level_0',   'Revenue per worker')],
           )

In [281]:
company_data.columns = company_data.columns.get_level_values(0)

In [282]:
company_data.columns

Index(['Rank', 'Name', 'Industry', 'Revenue', 'Profit', 'Employees',
       'Headquarters[note 1]', 'State-owned', 'Ref.', 'Unnamed: 9_level_0'],
      dtype='object')

In [283]:
company_data.head()

,Rank,Name,Industry,Revenue,Profit,Employees,Headquarters[note 1],State-owned,Ref.,Unnamed: 9_level_0
0,1,Walmart,Retail,"$611,289","$11,680",2100000,United States,NaN,[1],"291.090,00"
1,2,Saudi Aramco,Oil and gas,"$603,651","$159,069",70496,Saudi Arabia,NaN,[4],"8.562.911,37"
2,3,State Grid Corporation of China,Electricity,"$530,009","$8,192",870287,China,NaN,[5],"609.004,85"
3,4,Amazon,Retail,"$513,983","−$2,722",1541000,United States,NaN,[6],"333.538,61"
4,5,Vitol,Commodities,"$505,000","$15,000",1560,Switzerland,NaN,[7][8],"323.717.948,72"

In [284]:
# dropping the ref column

company_data.drop(columns=['Ref.', 'State-owned'], inplace=True)

### Renaming the columns

In [285]:
company_data.columns

Index(['Rank', 'Name', 'Industry', 'Revenue', 'Profit', 'Employees',
       'Headquarters[note 1]', 'Unnamed: 9_level_0'],
      dtype='object')

In [286]:
company_data.rename(columns =
                    {'Rank': 'Ranking',
                     'Name': 'Company Name',
                     'Revenue': 'Revenue(USD millions)',
                     'Profit': 'Profit(USD millions)',
                     'Headquarters[note 1]': 'Headquarters',
                    'Unnamed: 9_level_0': 'Revenue per worker'}, inplace=True
                    )

In [287]:
company_data.head()

,Ranking,Company Name,Industry,Revenue(USD millions),Profit(USD millions),Employees,Headquarters,Revenue per worker
0,1,Walmart,Retail,"$611,289","$11,680",2100000,United States,"291.090,00"
1,2,Saudi Aramco,Oil and gas,"$603,651","$159,069",70496,Saudi Arabia,"8.562.911,37"
2,3,State Grid Corporation of China,Electricity,"$530,009","$8,192",870287,China,"609.004,85"
3,4,Amazon,Retail,"$513,983","−$2,722",1541000,United States,"333.538,61"
4,5,Vitol,Commodities,"$505,000","$15,000",1560,Switzerland,"323.717.948,72"

In [288]:
# remove the dollar sign and comma from revenue and profit

company_data['Revenue(USD millions)'] = company_data['Revenue(USD millions)'].str.replace('[\$,]', '', regex=True).astype(float)
company_data['Profit(USD millions)'] = company_data['Profit(USD millions)'].str.replace('[^\d−]', '', regex=True)

In [289]:
# change the minus sign to a standard minus sign
# change the 'Profit(USD millions) to numeric values while omitting the empty column

company_data['Profit(USD millions)'] = company_data['Profit(USD millions)'].str.replace('−', '-', regex=True)
company_data['Profit(USD millions)'] = pd.to_numeric(company_data['Profit(USD millions)'], errors='coerce')

In [290]:
company_data.tail()

,Ranking,Company Name,Industry,Revenue(USD millions),Profit(USD millions),Employees,Headquarters,Revenue per worker
45,46,Baowu,Steel,161698.0,2493.0,245675,China,"658.178,49"
46,47,Schwarz Gruppe,Retail,159800.0,NaN,575000,Germany,"277.913,04"
47,48,Mitsubishi Group,Conglomerate,159371.0,8723.0,79706,Japan,"1.999.485,61"
48,49,Ford Motor Company,Automotive,158057.0,-1981.0,173000,United States,"913.624,28"
49,50,Mercedes-Benz Group,Automotive,157403.0,15252.0,168797,Germany,"932.498,80"

### Summary of the data

In [291]:
company_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Ranking                50 non-null     int64
 1   Company Name           50 non-null     object
 2   Industry               50 non-null     object
 3   Revenue(USD millions)  50 non-null     float64
 4   Profit(USD millions)   48 non-null     float64
 5   Employees              50 non-null     int64
 6   Headquarters           50 non-null     object
 7   Revenue per worker     50 non-null     object
dtypes: float64(2), int64(2), object(4)
memory usage: 3.2+ KB